version: '2'
services:
  couchexmp-app:
    image: couchexmp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_COUCHBASE_BOOTSTRAP_HOSTS=couchexmp-couchbase
      - SPRING_COUCHBASE_BUCKET_NAME=CouchExmp
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  couchexmp-couchbase:
    extends:
      file: couchbase.yml
      service: couchexmp-couchbase
